export const RATES_LOAD_INIT = "RATES_LOAD_INIT";
export const RATES_LOAD_SUCCEED = "RATES_LOAD_SUCCEED";
export const RATES_LOAD_FAILED = "RATES_LOAD_FAILED";

export const RATE_SAVE_INIT = "RATE_SAVE_INIT";
export const RATE_SAVE_SUCCEED = "RATE_SAVE_SUCCEED";
export const RATE_SAVE_FAILED = "RATE_SAVE_FAILED";

export const SET_ENTITY_TO_UPDATE = "SET_ENTITY_TO_UPDATE";

export const RATE_DELETE_INIT = "RATE_DELETE_INIT";
export const RATE_DELETE_SUCCEED = "RATE_DELETE_SUCCEED";
export const RATE_DELETE_FAILED = "RATE_DELETE_FAILED";



