export const LINKS_LOAD_INIT = "LINKS_LOAD_INIT";
export const LINKS_LOAD_SUCCEED = "LINKS_LOAD_SUCCEED";
export const LINKS_LOAD_FAILED = "LINKS_LOAD_FAILED";

export const LINK_SAVE_INIT = "LINK_SAVE_INIT";
export const LINK_SAVE_SUCCEED = "LINK_SAVE_SUCCEED";
export const LINK_SAVE_FAILED = "LINK_SAVE_FAILED";

export const LINK_DELETE_INIT = "LINK_DELETE_INIT";
export const LINK_DELETE_SUCCEED = "LINK_DELETE_SUCCEED";
export const LINK_DELETE_FAILED = "LINK_DELETE_FAILED";
